Add inactivity_policy.md
neoforged/governance pull request #13
Opened 2024-12-14 14:00 UTC by TelepathicGrunt

Adds a procedure to ensure that inactive members are purged over time and not kept on the team for decades

2024-12-14 16:06 UTC, IchHabeHunger54 requested changes
Typos and grammar, plus one small extra note about subteam members.

2024-12-14 16:06 UTC, IchHabeHunger54 commented on inactivity_policy.md
> +Like any other large projects, members on the NeoForge team may become inactive and stop contributing to the project over long periods of time. This document outline a policy to make sure that inacti
```suggestion
Like in any other large project, members on the NeoForged team may become inactive and stop contributing to the project over long periods of time. This document outlines a policy to make sure that inactive members are routinely removed from the team in order to keep the team size at a healthy amount and fully active.
```

2024-12-14 16:06 UTC, IchHabeHunger54 commented on inactivity_policy.md
> + * Intended to outline the procedure to prunning inactive Neoforged team members with minimal disagreements.
```suggestion
 * Intended to outline the procedure to pruning inactive Neoforged team members with minimal disagreements.
```

2024-12-14 16:06 UTC, IchHabeHunger54 commented on inactivity_policy.md
> +Every year, 2 months before the next planned Steering Council elections, the Steering Council members will review the list of all NeoForged team members. If a member has not been contributing for wha
```suggestion
Every year, 2 months before the next planned Steering Council elections, the Steering Council members will review the list of all NeoForged team members. If a member has not been contributing for what their role is for over at least 12 months (Maintainers working on projects, Moderators watching conversations, subteam members working on their respective subprojects), the Steering Council will begin following through these series of steps:
```

2024-12-14 16:06 UTC, IchHabeHunger54 commented on inactivity_policy.md
> + * If the member provides a reasonable excuse for their inactivity such as life situations getting in the way, they may be granted an extra year to remain on the team so they can have the time to get
```suggestion
 * If the member provides a reasonable excuse for their inactivity, such as life situations getting in the way, they may be granted an extra year to remain on the team so they can have the time to get back into contributing once they are available to do so. This grace period must be agreed upon by 2/3rds of the Steering Council.
```

2024-12-14 16:06 UTC, IchHabeHunger54 commented on inactivity_policy.md
> +Steering Council members cannot be put through this process as per the (voting.md)[voting.md] document, Steering Council are re-elected every year and thus, are routinely judged and replaced to ensur
```suggestion
Steering Council members cannot be put through this process as per the (voting.md)[voting.md] document. Steering Council are re-elected every year and thus are routinely judged and replaced to ensure there are always active council members.
```

2024-12-14 17:14 UTC, robotgryphon commented on inactivity_policy.md
> +Every year, 7 months before the next planned Steering Council elections, the Steering Council members will review the list of all NeoForged team members. If a member has not been contributing for wha
"for over at least" > "for over"

2024-12-19 20:06 UTC, IchHabeHunger54 approved these changes

2025-01-16 23:41 UTC, Technici4n commented on inactivity_policy.md
> +   * If no response, reach out to other members on the person's subteam to verify that the person is inactive in the role they were assigned.
Do we even still have a concept of subteam?

2025-01-16 23:41 UTC, Technici4n commented on inactivity_policy.md
> +   * If no response, reach out to other members on the person's subteam to verify that the person is inactive in the role they were assigned.
It should be sufficient to reach out to other team members.

2025-01-16 23:46 UTC, Technici4n approved these changes

2025-01-17 14:42 UTC, TheSilkMiner approved these changes
General approval, though I'd add a note about people with multiple roles to make it clear that they are considered separately for the purposes of the process, as per [this answer](<https://canary.discord.com/channels/313125603924639766/1317491699249057832/1329599256100868197>).

2025-01-17 15:48 UTC, TheSilkMiner approved these changes

2025-01-17 19:28 UTC, ChampionAsh5357 approved these changes

2025-01-23 23:38 UTC, merged